FROM openjdk:17-jdk-alpine3.14
ARG JAR_FILE=target/*.jar

ENV SECOND_PORT="${SECOND_PORT}"
ENV SECOND_HOST_PORT="${SECOND_HOST_PORT}"

ENV FIRST_PORT="${FIRST_PORT}"

ENV SECOND_DB_USER="${SECOND_DB_USER}"
ENV SECOND_DB_PASSWORD="${SECOND_DB_PASSWORD}"
ENV SECOND_DB="${SECOND_DB}"
ENV SECOND_DB_PORT="${SECOND_DB_PORT}"

ENV KAFKA_INSIDE_PORT="${KAFKA_INSIDE_PORT}"

COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar", "--spring.profiles.active=dev"]
