services:

  secondms:
    container_name: SecondMs
    image: second-microservice
    build:
      context: .
    ports:
      - "${SECOND_HOST_PORT:-8084}:${SECOND_PORT:-8083}"
    environment:
      - SECOND_PORT=${SECOND_PORT}
      - SECOND_HOST_PORT=${SECOND_HOST_PORT}
      - FIRST_PORT=${FIRST_PORT}
      - SECOND_DB_USER=${SECOND_DB_USER}
      - SECOND_DB_PASSWORD=${SECOND_DB_PASSWORD}
      - SECOND_DB=${SECOND_DB}
      - SECOND_DB_PORT=${SECOND_DB_PORT}
      - KAFKA_INSIDE_PORT=${KAFKA_INSIDE_PORT}
    depends_on:
      - seconddb
    networks:
      - ms-network

  seconddb:
    image: postgres:16.2
    container_name: SecondDb
    environment:
      POSTGRES_USER: ${SECOND_DB_USER}
      POSTGRES_PASSWORD: ${SECOND_DB_PASSWORD}
      POSTGRES_DB: ${SECOND_DB}
    ports:
      - "${SECOND_DB_PORT}:${SECOND_DB_PORT}"
    command: ["postgres", "-p", "${SECOND_DB_PORT}"]
    networks:
      - ms-network

networks:
  ms-network:
    external: true