server:
  port: ${SECOND_PORT:8083}

spring:
  application:
    name: SecondMs

  datasource:
    url: jdbc:postgresql://seconddb:${SECOND_DB_PORT}/${SECOND_DB}
    username: ${SECOND_DB_USER}
    password: ${SECOND_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: kafka:${KAFKA_INSIDE_PORT}
    consumer:
      group-id: group-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          trusted:
            packages: com.velb
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false

cluster:
  firstms:
    url: http://firstms:${FIRST_PORT:8085}/api/v1/first

  kafka:
    topic:
      first-topic: first-topic
      second-topic: second-topic