server:
  port: 8081

spring:
  application:
    name: SecondMs
  datasource:
    url: jdbc:postgresql://localhost:5433/second_db
    username: second_db_user
    password: second_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cluster:
  firstms:
    port: 8080
    host: localhost
    url: /api/v1/first